# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Check for new commits today
      id: check-new-commits
      uses: adriangl/check-new-commits-action@v1
      with:
        token: ${{ secrets.MYTOKEN }}
        seconds: 86400 # One day in seconds
        branch: 'master'
    - name: Print something if new commits are found
      if: ${{ steps.check-new-commits.outputs.has-new-commits == 'true' }}
      run: echo "You have ${{ steps.check-new-commits.outputs.new-commits-number }} new commit(s) ✅!"
    - name: Print another thing if new commits couldn't be found
      if: ${{ steps.check-new-commits.outputs.has-new-commits != 'true' }}
      run: echo "You don't have new commits 🛑!"
